### ISSUE TITLE
Añadid vuestros colorines

### ISSUE THREAD

**Issue by JJ** [geneura-papers/plantilla#1]
Vamos a usar el paquete todonotes de Latex para insertar notas en los papers. En el fichero `colores.tex` he elegido mis colores creando un nuevo comando \notajj.
Se trata de que cada uno creéis vuestro propio comando \notaxyz para insertar vuestras notas, con los colorines que más os guste y/o prefijos.
Y esto para todos @vrivas @gstvrmrlpz @mgarenas  @amorag @deantares @pacastillo @raiben @unintendedbear y si me he dejado a alguien, que lo meta también.

**Comment by vrivas** [comment]
Añadido el mío, y por lo que veo también el de Pedro.
Además, modifico el newcommand para que, después del texto de la nota, añada también el nombre del que la ha hecho. Con eso, además de identificarlo por color, lo tenemos identificado por nombre ;)

**Comment by JJ** [comment]
¡Guay!

**Comment by fergunet** [comment]
Ya he puesto la mía, pero no sé exactamente de qué color es (creo que rosa o algo así), si a alguien le sangran los ojos que lo cambie.

**Comment by amorag** [comment]
Yo he añadido la mía, pero en MikTex (el compilador de Latex de Windows) no veo na (sale una maraña de líneas), ni en el DVI, ni en el PDF… :_(

No sé si lo podré usar.

De: Pablo García Sánchez [mailto:notifications@github.com] 
Enviado el: domingo, 30 de noviembre de 2014 14:51
Para: geneura-papers/plantilla
CC: Antonio Mora
Asunto: Re: [plantilla] Añadid vuestros colorines (#1)

Ya he puesto la mía, pero no sé exactamente de qué color es (creo que rosa o algo así), si a alguien le sangran los ojos que lo cambie.

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/plantilla/issues/1#issuecomment-64985920 .  https://github.com/notifications/beacon/AC6-WjK0HcQlXTw0789tcKg-d27VPkquks5nSxhRgaJpZM4DCBPg.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2013.0.3495 / Base de datos de virus: 4189/8650 - Fecha de publicación: 11/29/14

**Comment by unintendedbear** [comment]
Yo también he añadido los míos. Y en plural, porque he definido dos verdes para mis cosicas.

**Comment by gstvrmrlpz** [comment]
añadido el mío y una sugerencia...

**Comment by fergunet** [comment]
@gstvrmrlpz no sale tu nombre en la nota al compilar

**Comment by deantares** [comment]
Que digo yo, que ya que hemos puesto la "firma" al final, ¿no sería mejor
usar los colores para la importancia o algo así? Es que yo estoy viendo que
no voy a ser capaz de recordar de quien es el color de cada uno [?].

Además, así dejamos una sola función, que se le pase el nombre, el color y
el comentario (en lugar de tener una función para cada uno).

De todos modos, voy a subir mi colorines xD

Antonio Fernández Ares  http://web.deantares.es
 [image: skype]  [image: facebook] http://www.facebook.com/antares.es [image:
twitter] http://twitter.com/#!/antaress [image: linkedIn]
http://www.linkedin.com/profile/view?id=97716796&locale=es_ES&trk=tab_pro
[image:
xing] http://www.xing.com/profile/Antonio_FernandezAres [image: xing]
https://plus.google.com/+AntonioFern%C3%A1ndezAres-Antares

[image: eco] No me imprimas si no es necesario. Protejamos el medio
ambiente. Muchas Gracias y esas cosas... [image: eco]

2014-12-01 16:10 GMT+01:00 Pablo García Sánchez notifications@github.com:

**Comment by rhgarcia** [comment]
Hombre... En un paper tampoco solemos escribir todos, creo. 3 o 4 personas
a lo sumo, y otras tantas esporádicas. No creo que sean tan lioso :-)
Por cierto, ¿nadie se ha cogido el fuksia con letras verdes aun? Genial,
¡estoy a tiempo!

2014-12-01 18:36 GMT+01:00 Antonio Fernández Ares notifications@github.com
:

**Comment by gstvrmrlpz** [comment]
arreglado
